version: '3.9'

services:
  tz:
    depends_on:
      - mongo
    build: .
    container_name: server
    ports:
      - "80:8080"
    environment:
      MONGODB_URI: "${MONGODB_URI}"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod
