version: '3.9'

services:
  tz:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI_ARG: "${MONGODB_URI}"
    container_name: server
    hostname: server
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      MONGODB_URI: "${MONGODB_URI}"
      MONGO_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    networks:
      - mongo_net
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongodb
    ports:
      - "27019:27019"
    expose:
      - "27019"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    command: mongod --port 27019
    networks:
      - mongo_net

volumes:
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge